version: '3.3'
services:
  baichuan:
    # image: registry.cn-hangzhou.aliyuncs.com/coldsnap/baichuan2-13b-chat.openai-api:v2 # baichuan2-13b-chat
    image: registry.cn-hangzhou.aliyuncs.com/coldsnap/baichuan2-7b-chat.openai-api:v2 # baichuan2-7b-chat
    container_name: baichuan
    restart: always
    ports:
      - 8001:8001
    networks:
      - llm
    environment:
      - SK_KEY=sk-abcdefghijkabcdefghijkabcdefghijk # 设置模型接口认证Token
      - QUANTIZE_BIT=16 # 设置模型量化程度（16/8/4）
      - NUM_WORKERS=1 # 设置 uvicorn 参数 workers 的数量
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1'] # 指定模型使用的GPU设备序号
              capabilities: [gpu]
  m3e:
    image: registry.cn-hangzhou.aliyuncs.com/coldsnap/m3e-large.openai-api:v2
    container_name: m3e
    restart: always
    ports:
      - 8002:8002
    networks:
      - llm
    environment:
      - SK_KEY=sk-abcdefghijkabcdefghijkabcdefghijk # 设置模型接口认证Token
      - NUM_WORKERS=1 # 设置 uvicorn 参数 workers 的数量
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['2'] # 指定模型使用的GPU设备序号
              capabilities: [gpu]
  reranker:
    image: registry.cn-hangzhou.aliyuncs.com/coldsnap/bge-reranker-base:v1
    container_name: reranker
    restart: always
    ports:
      - 8003:6006
    networks:
      - llm
    environment:
      - ACCESS_TOKEN=sk-abcdefghijkabcdefghijkabcdefghijk # 设置模型接口认证Token
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['3'] # 指定模型使用的GPU设备序号
              capabilities: [gpu]
  oneapi:
    image: justsong/one-api:latest
    container_name: oneapi
    restart: always
    command: --log-dir /app/logs
    ports:
      - 8000:3000
    network:
      - llm
    environment:
      - SQL_DSN=oneapi:123456@tcp(db:3306)/one-api  # 修改此行，或注释掉以使用 SQLite 作为数据库
      - REDIS_CONN_STRING=redis://redis
      - SESSION_SECRET=random_string  # 修改为随机字符串
      - TZ=Asia/Shanghai
#      - NODE_TYPE=slave  # 多机部署时从节点取消注释该行
#      - SYNC_FREQUENCY=60  # 需要定期从数据库加载数据时取消注释该行
#      - FRONTEND_BASE_URL=https://openai.justsong.cn  # 多机部署时从节点取消注释该行
    volumes:
      # 设置数据和日志本地保存目录
      - ./data/oneapi:/data
      - ./logs:/app/logs
    depends_on:
      - redis
      - db
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'" ]
      interval: 30s
      timeout: 10s
      retries: 3
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - llm
  db:
    image: mysql:8.2.0
    restart: always
    container_name: mysql
    networks:
      - llm
    volumes:
      - ./data/mysql:/var/lib/mysql  # 挂载目录，持久化存储
    environment:
      TZ: Asia/Shanghai   # 设置时区
      MYSQL_ROOT_PASSWORD: 'OneAPI@justsong' # 设置 root 用户的密码
      MYSQL_USER: oneapi   # 创建专用用户
      MYSQL_PASSWORD: '123456'    # 设置专用用户密码
      MYSQL_DATABASE: one-api   # 自动创建数据库
networks:
  llm:
